apiVersion: apps/v1
kind: Deployment
metadata:
  name: mywebserver
  labels:
    app: httpd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpd

  template:
    metadata:
      labels:
        app: httpd
    spec:
      containers:
        - name: myhttpd
          image: httpd
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /data
              name: demovol
            - mountPath: /etc/config
              name: demo-configmap
            - mountPath: /etc/mysecret
              name: demo-secret
            - mountPath: /data/clustervol
              name: demo-pvc
      volumes:
        - name: demovol
          hostPath:
            path: /data
            type: Directory
        - name: demo-configmap
          configMap:
            name: demo-configmap
        - name: demo-secret
          secret:
            secretName: demo-secret
        - name: demo-pvc
          persistentVolumeClaim:
            claimName: demo-pvc

