version: '3'

networks:
  mynetwork:
    driver: bridge

volumes:
  myvolume:

services:
  docker-mysql:
    container_name: docker-mysql
    image: mysql
    ports: [6666:3306]
    networks: [mynetwork]
    volumes: [myvolume:/var/lib/mysql]
    environment: [MYSQL_ROOT_PASSWORD=test1234, MYSQL_DATABASE=mydb]

  coupon-service:
    container_name: coupon-service
    image: kermant11/coupon-service
    ports: [8081:8080]
    networks: [mynetwork]
    depends_on: [docker-mysql]

  product-service:
    container_name: product-service
    image: kermant11/product-service
    ports: [8082:8080]
    networks: [mynetwork]
    depends_on: [docker-mysql,coupon-service]
