apiVersion: apps/v1
kind: Deployment
metadata:
  name: coupon-service
  labels:
    app: coupon-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coupon-service

  template:
    metadata:
      name: coupon-service
      labels:
        app: coupon-service
    spec:
      containers:
        - name: coupon-service
          image: kermant11/coupon-service
