apiVersion: v1
kind: Service
metadata:
  name: coupon-service
  labels:
    app: coupon-service
spec:
  type: NodePort
  selector:
    app: coupon-service
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30081

