spring:
  datasource:
    url: jdbc:mysql://moj-db-instance.cu930wrval0v.eu-central-1.rds.amazonaws.com:3306/mydb
    username: root
    password: test1234
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update

server:
  port: 5000

couponservice.url: http://couponservice-env.eba-agdcemry.eu-central-1.elasticbeanstalk.com/api/coupons/
